### ISSUE TITLE
Error on ReConnecting to Arcam Device

### ISSUE THREAD

**Issue by HenrikGeiger** [docbobo/roon-extension-arcam#1]
### Reconnecting to Arcam device not working

The plugin is successfully connected to the arcam. If the arcam is switched off and after some time on again (not only standby. Arcam Device is completly disconnected from power because it is plugged into a switchable wall plug) the plugin does not automatically reconnect to the arcam. 
The Status is: `"Connection closed. Reconnecting..."` and I can't control the volume with roon.
After a plugin restart it works again. 

The following error appears in the log:

`(node:154388) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 heartbeat listeners added to [ArcamClient]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:390:17)
    at ArcamClient.addListener (events.js:406:10)
    at ArcamClient.once (events.js:437:8)
    at /home/***********/roon-extension-arcam/arcam_client/arcam_client.js:132:22
    at Promise._execute (/home/***********/roon-extension-arcam/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/home/***********/roon-extension-arcam/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/home/***********/roon-extension-arcam/node_modules/bluebird/js/release/promise.js:103:10)
    at ArcamClient.sendCommand (/home/***********/roon-extension-arcam/arcam_client/arcam_client.js:130:16)
    at ArcamClient.heartbeat (/home/***********/roon-extension-arcam/arcam_client/arcam_client.js:197:21)
    at Timeout._onTimeout (/home/***********/roon-extension-arcam/app.js:126:26)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)`

I guess that some eventlisteners are not being removed correctly if the connection cannot be established succesful. Is that correct? Can anyone help me with this problem?

**Comment by docbobo** [comment]
Interesting.  Not  sure if this is a red herring or  not though.

Heartbeat is  registering an event listener every time, but  due  to the lost connection it's never being called and will only be removed when the  next response comes in. That's  certainly leaking and needs a fix  that I am not yet completely clear  on.

Not sure if that explains the fact  that you cannot communicate with the AVR once turned on  again. Need to look into that.

**Comment by HenrikGeiger** [comment]
Thanks for your response.
If you need any further information or logs regarding this issue please feel free to ask.
